create extension if not exists vector
with schema extensions;

create table public.news_articles (
  slug text primary key,
  category text not null,
  region text not null,
  title text not null,
  author text not null,
  published_at date not null,
  read_time text not null,
  source_count integer not null check (source_count >= 0),
  image_url text not null,
  image_position text,
  caption text not null,
  bias_left smallint not null check (bias_left between 0 and 100),
  bias_center smallint not null check (bias_center between 0 and 100),
  bias_right smallint not null check (bias_right between 0 and 100),
  body text[] not null default '{}',
  summary text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint news_articles_bias_total check (bias_left + bias_center + bias_right between 99 and 101)
);

create table public.news_article_sources (
  id bigint generated by default as identity primary key,
  article_slug text not null references public.news_articles (slug) on delete cascade,
  name text not null,
  bias text not null check (bias in ('Left', 'Center', 'Right')),
  source_url text,
  created_at timestamptz not null default now()
);

create table public.sources (
  id bigint generated by default as identity primary key,
  name text not null unique,
  listing_url text not null unique,
  parser_strategy text not null default 'generic',
  logo_url text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.articles (
  id bigint generated by default as identity primary key,
  source_id bigint not null references public.sources (id) on delete restrict,
  original_url text not null unique,
  canonical_url text not null unique,
  title text not null,
  image_url text not null,
  published_at timestamptz not null,
  raw_text text not null,
  scraped_at timestamptz not null default now(),
  analyzed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.article_analyses (
  id bigint generated by default as identity primary key,
  article_id bigint not null unique references public.articles (id) on delete cascade,
  summary text not null,
  sentiment_score numeric(4,3) not null check (sentiment_score between -1 and 1),
  sentiment_label text not null check (sentiment_label in ('positive', 'neutral', 'negative')),
  bias_score numeric(4,3) not null check (bias_score between -1 and 1),
  bias_label text not null check (bias_label in ('left', 'center', 'right', 'mixed', 'unclear')),
  left_percentage smallint not null check (left_percentage between 0 and 100),
  center_percentage smallint not null check (center_percentage between 0 and 100),
  right_percentage smallint not null check (right_percentage between 0 and 100),
  confidence numeric(4,3) not null check (confidence between 0 and 1),
  framing_notes text not null,
  loaded_terms text[] not null default '{}',
  disclaimer text not null,
  model text not null,
  embedding extensions.vector(1536),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint article_analyses_percent_total check (left_percentage + center_percentage + right_percentage = 100)
);

create table public.logs (
  id bigint generated by default as identity primary key,
  event_type text not null,
  level text not null default 'info' check (level in ('debug', 'info', 'warn', 'error')),
  message text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.oxylabs_schedules (
  id bigint generated by default as identity primary key,
  source_id bigint not null unique references public.sources (id) on delete cascade,
  schedule_id text not null unique,
  cron text not null,
  active boolean not null default true,
  last_synced_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.oxylabs_schedule_runs (
  id bigint generated by default as identity primary key,
  schedule_id text not null,
  oxylabs_job_id text not null unique,
  source_id bigint not null references public.sources (id) on delete cascade,
  result_status text not null,
  processed_at timestamptz,
  inserted_count integer not null default 0,
  rejected_count integer not null default 0,
  failed_count integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index news_articles_published_at_idx
  on public.news_articles (published_at desc, slug);

create index news_articles_category_published_at_idx
  on public.news_articles (category, published_at desc);

create index news_articles_region_published_at_idx
  on public.news_articles (region, published_at desc);

create index news_article_sources_article_slug_idx
  on public.news_article_sources (article_slug);

create index sources_active_idx
  on public.sources (active, name);

create index articles_source_id_idx
  on public.articles (source_id);

create index articles_published_at_idx
  on public.articles (published_at desc);

create index articles_analyzed_at_idx
  on public.articles (analyzed_at)
  where analyzed_at is null;

create index article_analyses_article_id_idx
  on public.article_analyses (article_id);

create index article_analyses_embedding_ivfflat_idx
  on public.article_analyses
  using ivfflat (embedding extensions.vector_cosine_ops)
  with (lists = 100)
  where embedding is not null;

create index logs_event_created_at_idx
  on public.logs (event_type, created_at desc);

create index oxylabs_schedules_source_id_idx
  on public.oxylabs_schedules (source_id);

create index oxylabs_schedule_runs_source_id_idx
  on public.oxylabs_schedule_runs (source_id);

create index oxylabs_schedule_runs_processed_at_idx
  on public.oxylabs_schedule_runs (processed_at)
  where processed_at is null;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.match_related_articles(
  query_embedding extensions.vector(1536),
  match_article_id bigint,
  match_count integer default 5
)
returns table (
  id bigint,
  title text,
  image_url text,
  published_at timestamptz,
  source_name text,
  bias_label text,
  left_percentage smallint,
  center_percentage smallint,
  right_percentage smallint,
  confidence numeric,
  similarity double precision
)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    articles.id,
    articles.title,
    articles.image_url,
    articles.published_at,
    sources.name as source_name,
    article_analyses.bias_label,
    article_analyses.left_percentage,
    article_analyses.center_percentage,
    article_analyses.right_percentage,
    article_analyses.confidence,
    1 - (article_analyses.embedding <=> query_embedding) as similarity
  from public.article_analyses
  join public.articles
    on articles.id = article_analyses.article_id
  join public.sources
    on sources.id = articles.source_id
  where article_analyses.embedding is not null
    and articles.analyzed_at is not null
    and articles.id <> match_article_id
  order by article_analyses.embedding <=> query_embedding
  limit least(greatest(match_count, 1), 20);
$$;

create or replace function public.pending_articles_for_analysis(
  match_count integer default 5,
  excluded_article_ids bigint[] default '{}'::bigint[],
  selected_article_ids bigint[] default null
)
returns table (
  id bigint,
  title text,
  raw_text text,
  analysis_id bigint,
  needs_full_analysis boolean,
  needs_embedding boolean
)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    articles.id,
    articles.title,
    articles.raw_text,
    article_analyses.id as analysis_id,
    article_analyses.id is null as needs_full_analysis,
    article_analyses.id is not null and article_analyses.embedding is null as needs_embedding
  from public.articles
  left join public.article_analyses
    on article_analyses.article_id = articles.id
  where (
      article_analyses.id is null
      or article_analyses.embedding is null
    )
    and not (articles.id = any(excluded_article_ids))
    and (
      selected_article_ids is null
      or articles.id = any(selected_article_ids)
    )
  order by articles.scraped_at asc
  limit least(greatest(match_count, 1), 20);
$$;

create trigger set_news_articles_updated_at
before update on public.news_articles
for each row
execute function public.set_updated_at();

create trigger set_sources_updated_at
before update on public.sources
for each row
execute function public.set_updated_at();

create trigger set_articles_updated_at
before update on public.articles
for each row
execute function public.set_updated_at();

create trigger set_article_analyses_updated_at
before update on public.article_analyses
for each row
execute function public.set_updated_at();

create trigger set_oxylabs_schedules_updated_at
before update on public.oxylabs_schedules
for each row
execute function public.set_updated_at();

alter table public.news_articles enable row level security;
alter table public.news_article_sources enable row level security;
alter table public.sources enable row level security;
alter table public.articles enable row level security;
alter table public.article_analyses enable row level security;
alter table public.logs enable row level security;
alter table public.oxylabs_schedules enable row level security;
alter table public.oxylabs_schedule_runs enable row level security;

create policy "Public can read published news articles"
on public.news_articles
for select
to anon, authenticated
using (published_at <= current_date);

create policy "Public can read sources for published articles"
on public.news_article_sources
for select
to anon, authenticated
using (
  exists (
    select 1
    from public.news_articles
    where news_articles.slug = news_article_sources.article_slug
      and news_articles.published_at <= current_date
  )
);

create policy "Public can read active sources"
on public.sources
for select
to anon, authenticated
using (active = true);

create policy "Public can read analyzed articles"
on public.articles
for select
to anon, authenticated
using (analyzed_at is not null);

create policy "Public can read analyses for analyzed articles"
on public.article_analyses
for select
to anon, authenticated
using (
  exists (
    select 1
    from public.articles
    where articles.id = article_analyses.article_id
      and articles.analyzed_at is not null
  )
);

grant select on public.news_articles to anon, authenticated;
grant select on public.news_article_sources to anon, authenticated;
grant select on public.sources to anon, authenticated;
grant select on public.articles to anon, authenticated;
grant select on public.article_analyses to anon, authenticated;

grant all on public.news_articles to service_role;
grant all on public.news_article_sources to service_role;
grant all on public.sources to service_role;
grant all on public.articles to service_role;
grant all on public.article_analyses to service_role;
grant all on public.logs to service_role;
grant all on public.oxylabs_schedules to service_role;
grant all on public.oxylabs_schedule_runs to service_role;

grant usage, select on sequence public.news_article_sources_id_seq to service_role;
grant usage, select on sequence public.sources_id_seq to service_role;
grant usage, select on sequence public.articles_id_seq to service_role;
grant usage, select on sequence public.article_analyses_id_seq to service_role;
grant usage, select on sequence public.logs_id_seq to service_role;
grant usage, select on sequence public.oxylabs_schedules_id_seq to service_role;
grant usage, select on sequence public.oxylabs_schedule_runs_id_seq to service_role;

grant execute on function public.match_related_articles(extensions.vector(1536), bigint, integer)
to anon, authenticated, service_role;

grant execute on function public.pending_articles_for_analysis(integer, bigint[], bigint[])
to service_role;
