create table public.news_articles (
  slug text primary key,
  category text not null,
  region text not null,
  title text not null,
  author text not null,
  published_at date not null,
  read_time text not null,
  source_count integer not null check (source_count >= 0),
  image_url text not null,
  image_position text,
  caption text not null,
  bias_left smallint not null check (bias_left between 0 and 100),
  bias_center smallint not null check (bias_center between 0 and 100),
  bias_right smallint not null check (bias_right between 0 and 100),
  body text[] not null default '{}',
  summary text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint news_articles_bias_total check (bias_left + bias_center + bias_right between 99 and 101)
);

create table public.news_article_sources (
  id bigint generated by default as identity primary key,
  article_slug text not null references public.news_articles (slug) on delete cascade,
  name text not null,
  bias text not null check (bias in ('Left', 'Center', 'Right')),
  source_url text,
  created_at timestamptz not null default now()
);

create index news_articles_published_at_idx
  on public.news_articles (published_at desc, slug);

create index news_articles_category_published_at_idx
  on public.news_articles (category, published_at desc);

create index news_articles_region_published_at_idx
  on public.news_articles (region, published_at desc);

create index news_article_sources_article_slug_idx
  on public.news_article_sources (article_slug);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger set_news_articles_updated_at
before update on public.news_articles
for each row
execute function public.set_updated_at();

alter table public.news_articles enable row level security;
alter table public.news_article_sources enable row level security;

create policy "Public can read published news articles"
on public.news_articles
for select
to anon, authenticated
using (published_at <= current_date);

create policy "Public can read sources for published articles"
on public.news_article_sources
for select
to anon, authenticated
using (
  exists (
    select 1
    from public.news_articles
    where news_articles.slug = news_article_sources.article_slug
      and news_articles.published_at <= current_date
  )
);

grant select on public.news_articles to anon, authenticated;
grant select on public.news_article_sources to anon, authenticated;
grant all on public.news_articles to service_role;
grant all on public.news_article_sources to service_role;
grant usage, select on sequence public.news_article_sources_id_seq to service_role;
